# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('time', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('amount', models.CharField(blank=True, max_length=40)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['finished'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 21, 7, 47, 951900)),
        ),
    ]
