# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161028_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 16, 12, 40, 801923)),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 16, 12, 40, 803793)),
        ),
    ]
