# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161028_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 11, 17, 27, 368161)),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 29, 11, 17, 27, 369539)),
        ),
    ]
