# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161029_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=datetime.datetime(2016, 10, 30, 21, 16, 51, 245990))),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 21, 16, 51, 244079)),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 30, 21, 16, 51, 245549)),
        ),
    ]
